//gli users a e AAA hanno lo stesso gamingProfile
//gli users b e BBB hanno lo stesso gamingProfile
//gli users c e CCC hanno lo stesso gamingProfile


const UsersFullProfiles = JSON.parse(
  {
    blankGamingProfile: {
      platform: "",
      gameMap: "",
      mode: "",
      kd: "",
      gameStyle: "",
      mic: "",
      lang: "",
      days: "",
      time: "",
      timeZone: "",
      emailAddress: "",
      gamebuddyUsername: "",
      password: "",
      warzoneUsername: "",
    },
    platform: "Xbox",
    gameMap: "Caldera",
    mode: "Duos",
    kd: "0.01",
    gameStyle: "Casual",
    mic: "Yes",
    lang: "English",
    days: "Monday-Friday",
    time: "9-11",
    timeZone: "GMT",
    emailAddress: "ale1a1@libero.it",
    gamebuddyUsername: "a",
    password: "a",
    warzoneUsername: "a",
  },
  {
    blankGamingProfile: {
      platform: "",
      gameMap: "",
      mode: "",
      kd: "",
      gameStyle: "",
      mic: "",
      lang: "",
      days: "",
      time: "",
      timeZone: "",
      emailAddress: "",
      gamebuddyUsername: "",
      password: "",
      warzoneUsername: "",
    },
    platform: "Play Station",
    gameMap: "Caldera Vanguard",
    mode: "Trios",
    kd: "0.02",
    gameStyle: "Aggressive pusher",
    mic: "No",
    lang: "Spanish",
    days: "Weekend",
    time: "7-9",
    timeZone: "PST",
    emailAddress: "ale1a184@gmail.com",
    gamebuddyUsername: "b",
    password: "b",
    warzoneUsername: "b",
  },
  {
    blankGamingProfile: {
      platform: "",
      gameMap: "",
      mode: "",
      kd: "",
      gameStyle: "",
      mic: "",
      lang: "",
      days: "",
      time: "",
      timeZone: "",
      emailAddress: "",
      gamebuddyUsername: "",
      password: "",
      warzoneUsername: "",
    },
    platform: "Computer",
    gameMap: "Rebirth",
    mode: "Quads",
    kd: "0.03",
    gameStyle: "Strategic",
    mic: "Yes",
    lang: "French",
    days: "Monday-Friday",
    time: "9-11",
    timeZone: "EST",
    emailAddress: "amwellvets@gmail.com",
    gamebuddyUsername: "c",
    password: "c",
    warzoneUsername: "c",
  },
  {
    blankGamingProfile: {
      platform: "",
      gameMap: "",
      mode: "",
      kd: "",
      gameStyle: "",
      mic: "",
      lang: "",
      days: "",
      time: "",
      timeZone: "",
      emailAddress: "",
      gamebuddyUsername: "",
      password: "",
      warzoneUsername: "",
    },
    platform: "Xbox",
    gameMap: "Caldera",
    mode: "Duos",
    kd: "0.01",
    gameStyle: "Casual",
    mic: "Yes",
    lang: "English",
    days: "Monday-Friday",
    time: "9-11",
    timeZone: "GMT",
    emailAddress: "ale1a1@libero.itAAA",
    gamebuddyUsername: "AAA",
    password: "AAA",
    warzoneUsername: "AAA",
  },
  {
    blankGamingProfile: {
      platform: "",
      gameMap: "",
      mode: "",
      kd: "",
      gameStyle: "",
      mic: "",
      lang: "",
      days: "",
      time: "",
      timeZone: "",
      emailAddress: "",
      gamebuddyUsername: "",
      password: "",
      warzoneUsername: "",
    },
    platform: "Play Station",
    gameMap: "Caldera Vanguard",
    mode: "Trios",
    kd: "0.02",
    gameStyle: "Aggressive pusher",
    mic: "No",
    lang: "Spanish",
    days: "Weekend",
    time: "7-9",
    timeZone: "PST",
    emailAddress: "ale1a184@gmail.comBBB",
    gamebuddyUsername: "BBB",
    password: "BBB",
    warzoneUsername: "BBB",
  },
  {
    blankGamingProfile: {
      platform: "",
      gameMap: "",
      mode: "",
      kd: "",
      gameStyle: "",
      mic: "",
      lang: "",
      days: "",
      time: "",
      timeZone: "",
      emailAddress: "",
      gamebuddyUsername: "",
      password: "",
      warzoneUsername: "",
    },
    platform: "Computer",
    gameMap: "Rebirth",
    mode: "Quads",
    kd: "0.03",
    gameStyle: "Strategic",
    mic: "Yes",
    lang: "French",
    days: "Monday-Friday",
    time: "9-11",
    timeZone: "EST",
    emailAddress: "amwellvets@gmail.comCCC",
    gamebuddyUsername: "CCC",
    password: "CCC",
    warzoneUsername: "CCC",
  }
);
